title: "Aditya Khanna"
description: "Blog Notes"
theme: minima

# Treat existing /posts folder as a posts collection
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/


